{% set version = "0.20.7" %}

package:
  name: metakernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/metakernel/metakernel-{{ version }}.tar.gz
  sha256: 33d53f987280b8348054443c2b6545afd55b2aac331346bf5265e199c14d4411

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - ipykernel
    - pexpect >=4.2

test:
  imports:
    - metakernel
    - metakernel.magics
    - metakernel.magics.tests
    - metakernel.tests
    - metakernel.utils

about:
  home: https://github.com/Calysto/metakernel
  license: BSD 3-Clause
  summary: 'Metakernel for Jupyter.'

extra:
  recipe-maintainers:
    - ocefpaf
    - ericdill
    - mariusvniekerk
    - blink1073
    - dsblank
