{% set version = "0.21.3" %}

package:
  name: metakernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/metakernel/metakernel-{{ version }}.tar.gz
  sha256: 0f8e913a7d08345694c0486e58fb086b273ef985f009b9caa41fa0491d6730cd

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - ipykernel
    - pexpect >=4.2

test:
  imports:
    - metakernel
    - metakernel.magics
    - metakernel.magics.tests
    - metakernel.tests
    - metakernel.utils

about:
  home: https://github.com/Calysto/metakernel
  license: BSD 3-Clause
  summary: 'Metakernel for Jupyter.'

extra:
  recipe-maintainers:
    - ocefpaf
    - ericdill
    - mariusvniekerk
    - blink1073
    - dsblank
