{% set version = "0.13.4" %}

package:
    name: metakernel
    version: {{ version }}

source:
    fn: metakernel-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/m/metakernel/metakernel-{{ version }}.tar.gz
    sha256: 2cd196dd14b64bee38b13962b364c828023074e6c1ac63077b8543439d6a372d

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - jupyter
        - gnureadline  # [osx]

test:
    imports:
        - metakernel
        - metakernel.magics
        - metakernel.magics.tests
        - metakernel.tests
        - metakernel.utils

about:
    home: https://github.com/Calysto/metakernel
    license: BSD 3-Clause
    summary: 'Metakernel for Jupyter.'

extra:
    recipe-maintainers:
        - ocefpaf
