{% set version = "0.21.3" %}

package:
  name: metakernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/metakernel/metakernel-{{ version }}.tar.gz
  sha256: 0f8e913a7d08345694c0486e58fb086b273ef985f009b9caa41fa0491d6730cd

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - ipykernel
    - pexpect >=4.2

test:
  imports:
    - metakernel
    - metakernel.magics
    - metakernel.magics.tests
    - metakernel.tests
    - metakernel.utils

about:
  home: https://github.com/Calysto/metakernel
  license: BSD 3-Clause
  summary: 'Metakernel for Jupyter.'
  description: |
      A Jupyter/IPython kernel template which includes core magic functions
      (including help, command and file path completion, parallel and
      distributed processing, downloads, and much more).
  dev_url: https://github.com/Calysto/metakernel
  doc_url: http://calysto.github.io/metakernel
  doc_source_url: https://github.com/Calysto/metakernel/tree/master/docs/source

extra:
  recipe-maintainers:
    - ocefpaf
    - ericdill
    - mariusvniekerk
    - blink1073
    - dsblank
