{% set version = "0.20.3" %}

package:
  name: metakernel
  version: {{ version }}

source:
  fn: metakernel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/metakernel/metakernel-{{ version }}.tar.gz
  sha256: 0f8ac10bb9c70df7866abe41a059aeebe5ea76e4bce99b8fb83c555efa515d21

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - ipykernel
    - pexpect >=4.2
    - gnureadline  # [osx]

test:
  imports:
    - metakernel
    - metakernel.magics
    - metakernel.magics.tests
    - metakernel.tests
    - metakernel.utils

about:
  home: https://github.com/Calysto/metakernel
  license: BSD 3-Clause
  summary: 'Metakernel for Jupyter.'

extra:
  recipe-maintainers:
    - ocefpaf
    - ericdill
    - mariusvniekerk
    - blink1073
    - dsblank
