{% set version = "0.12.6" %}

package:
    name: metakernel
    version: {{ version }}

source:
    fn: metakernel-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/m/metakernel/metakernel-{{ version }}.tar.gz
    sha256: 8de57c4419f125c8de6aa74cb09f346220d1e595ba09e20070f2640798d88d98

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - jupyter
        - gnureadline  # [osx]
    run:
        - python
        - jupyter
        - gnureadline  # [osx]

test:
    imports:
        - metakernel
        - metakernel.magics
        - metakernel.magics.tests
        - metakernel.tests
        - metakernel.utils

about:
    home: https://github.com/Calysto/metakernel
    license: BSD 3-Clause
    summary: Metakernel for Jupyter

extra:
    recipe-maintainers:
        - ocefpaf
