travis:
  secure:
    BINSTAR_TOKEN: XkgBDJyqLe85eA/y6tfQ53SQ+v6BDSlzPjRuYIMiKoGybD7TwVOWFyInKM6C6Ma6Z98bQstOB8Y3paAfgYRSL8i45P1HH2I8ikxLqCo0/Ecur6AsoG0T7pANNrYp93XRbTxLNX8/kptfNQO618d/LcGBhZvd6tzZsTwliiZtBpAKvq0/RZdoOWqYHqFQD38O2r17+jX0J9c16vvOO8E3gxsWdkX/fO+MViJkxZCroiY+esmafZYWCfvu/wseG1S4VdAfDVIsm8QGx93Sj9sIAfRY5kBMm+EllxGdVjEhvIXfZnyrrq00XAVEy1DlNKWCs7ANx9SYeGDk7NxsfDOqWyvwRqf+p6UvMJBRO11kw4PnVRCe15CsvZ8WjSC6pdq+vLdjGzP+6BkUEz6Emmahhmml2l3ExmPYI2KRMEoFkVi/sNh37RWmjnBJQT8gkinr2ifSOzNflOSljaajsa0qGEMDOgYW4o0Cc6kxcGTjFA4SFeg8Z1O0kIAun9zJ85wEBNM/2MFtY7KW+sO7G0EuSN4fUG6tnwmjtxd066bX4F229POxretBNYxDnDq2CJndpGCu+UOKAGn3e4kmLgDTcL6pm4HLqo10cAvaNmvWfvVm+Ulums1aTzA7DjmURQzYERCkshRi7kpdBL6TfLDViOY4EoWKAg1GOuRsCmEHv50=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
